# Generated by Django 5.0.7 on 2024-08-10 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryDate', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('power', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('entryDate', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalDept', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('entryDate', models.DateField(auto_now_add=True)),
                ('dateOnBill', models.DateField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.household')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdAppliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryDate', models.DateField(auto_now_add=True)),
                ('dateOnBill', models.DateField()),
                ('quantity', models.IntegerField(default=0)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.appliance')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.household')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryDate', models.DateTimeField(auto_now_add=True)),
                ('dateOnBill', models.DateField()),
                ('refuseBill', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('electricityBill', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('waterBill', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NumberOfIndividuals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfIndividuals', models.IntegerField()),
                ('entryDate', models.DateField(auto_now_add=True)),
                ('dateOnBill', models.DateField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.household')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryDate', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.household')),
            ],
        ),
    ]
