# Generated by Django 5.0.7 on 2024-08-11 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debt',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.household'),
        ),
        migrations.AlterField(
            model_name='household',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='householdappliance',
            name='appliance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.appliance'),
        ),
        migrations.AlterField(
            model_name='householdappliance',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.household'),
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='numberofindividuals',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.household'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.household'),
        ),
    ]
