# Generated by Django 5.0.7 on 2024-07-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilbill',
            name='billDate',
            field=models.DateField(),
        ),
    ]
