# Generated by Django 5.0.7 on 2024-07-26 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numberofindividuals',
            old_name='NumberOfIndividuals',
            new_name='numberOfIndividuals',
        ),
    ]
