# Generated by Django 5.0.7 on 2024-07-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_rename_numberofindividuals_numberofindividuals_numberofindividuals'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdappliance',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
