# Generated by Django 5.0.7 on 2024-08-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_household_image_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='image',
            field=models.ImageField(default='householdImages/defaultImage.jpg', upload_to='householdImages'),
        ),
    ]
