# Generated by Django 5.0.7 on 2024-07-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_householdappliance_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='power',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
