# Generated by Django 5.0.7 on 2024-07-17 06:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_alter_utilbill_dustbinbill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
