# Generated by Django 5.0.7 on 2024-07-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_household_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=10)),
            ],
        ),
    ]
