# Generated by Django 5.0.7 on 2024-07-29 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_household_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='credit',
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('entryDate', models.DateField(auto_now_add=True)),
                ('dateOnBill', models.DateField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.household')),
            ],
        ),
    ]
