# Generated by Django 5.0.7 on 2024-08-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='userImage/defaultImage.jpg', upload_to='userImage'),
        ),
    ]
