# Generated by Django 5.0.7 on 2024-09-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_alter_household_image_alter_userprofilepic_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
