name: Send Request
on:
  push:
    branches:
      - main
    
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: https://utilitydistribution.pythonanywhere.com/git_update'
        method: 'POST'
        headers: |
          '{"Content-Type": "application/json"}'
        data: '{"key_1": "value_1", "key_2": "value_2"}'
              